---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	request_classifier(request_classifier)
	clarify_constraints(clarify_constraints)
	rebooking_agent(rebooking_agent)
	refund_agent(refund_agent)
	compensation_agent(compensation_agent)
	policy_checker(policy_checker)
	escalation_agent(escalation_agent)
	final_response_agent(final_response_agent)
	tools(tools)
	__end__([<p>__end__</p>]):::last
	__start__ --> request_classifier;
	clarify_constraints -.-> rebooking_agent;
	compensation_agent -. &nbsp;__end__&nbsp; .-> policy_checker;
	compensation_agent -.-> tools;
	escalation_agent --> final_response_agent;
	policy_checker -.-> compensation_agent;
	policy_checker -.-> escalation_agent;
	policy_checker -.-> final_response_agent;
	policy_checker -.-> rebooking_agent;
	policy_checker -.-> refund_agent;
	rebooking_agent -. &nbsp;__end__&nbsp; .-> policy_checker;
	rebooking_agent -.-> tools;
	refund_agent -. &nbsp;__end__&nbsp; .-> policy_checker;
	refund_agent -.-> tools;
	request_classifier -.-> clarify_constraints;
	request_classifier -.-> compensation_agent;
	request_classifier -.-> escalation_agent;
	request_classifier -.-> refund_agent;
	tools -.-> compensation_agent;
	tools -.-> rebooking_agent;
	tools -.-> refund_agent;
	final_response_agent --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
